"""empty message

Revision ID: 20766146438c
Revises: 
Create Date: 2020-07-18 14:55:29.826449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20766146438c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_1', sa.Integer(), nullable=True),
    sa.Column('player_2', sa.Integer(), nullable=True),
    sa.Column('phrase_id_1', sa.Integer(), nullable=True),
    sa.Column('phrase_id_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phrase_id_1'], ['phrases.id'], ),
    sa.ForeignKeyConstraint(['phrase_id_2'], ['phrases.id'], ),
    sa.ForeignKeyConstraint(['player_1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('users')
    op.drop_table('phrases')
    # ### end Alembic commands ###
